/**
 * Angol-magyar futballnyelvi lexikon (2026-07-28-i sprint) — a Hungarian
 * Writer és az Editorial Rewrite Agent prompt-jaiba kötve be (lásd
 * hungarian-writer/generation.ts, editorial-rewrite/rewrite.ts), hogy a
 * modell ne fordítsa tükörfordításban az angol átigazolási nyelvet, brit
 * szlenget, mérkőzésbeszámoló-fordulatokat, taktikai kifejezéseket,
 * sérülés-/kerethíreket és edzői/játékos-idézeteket, hanem a valódi magyar
 * sportsajtóban (Nemzeti Sport, M4 Sport, Eurosport HU, Origo Sport)
 * használt természetes megfelelőt válassza.
 *
 * Forrás-formátum kompakt tuple, hogy a fájl kezelhető méretű maradjon 300+
 * tétel mellett is — a modul betöltéskor egyszer alakítja `LexiconEntry[]`
 * objektumokká (lásd lent), a hívó kód innentől csak azzal dolgozik.
 */

export type LexiconCategory =
  | "transfer"
  | "match_report"
  | "tactics"
  | "injury_squad"
  | "quotes"
  | "slang_idiom";

export interface LexiconEntry {
  category: LexiconCategory;
  /** Angol kifejezés. */
  en: string;
  /** Pontos jelentés futballkontextusban (magyarul). */
  meaningHu: string;
  /** Természetes magyar megfelelő. */
  naturalHu: string;
  /** Kerülendő tükörfordítás. */
  avoidLiteralHu: string;
  /** Példa angol mondat. */
  exampleEn: string;
  /** Jó magyar fordítás. */
  exampleHu: string;
}

type LexiconTuple = [
  category: LexiconCategory,
  en: string,
  meaningHu: string,
  naturalHu: string,
  avoidLiteralHu: string,
  exampleEn: string,
  exampleHu: string,
];

const RAW: LexiconTuple[] = [
  // ---------------------------------------------------------------------
  // ÁTIGAZOLÁSI NYELV (transfer)
  // ---------------------------------------------------------------------
  [
    "transfer",
    "transfer window",
    "az az időszak, amikor klubok igazolhatnak",
    "átigazolási időszak",
    "átigazolási ablak",
    "The transfer window closes on 1 September.",
    "Az átigazolási időszak szeptember 1-jén zárul.",
  ],
  [
    "transfer",
    "loan move",
    "ideiglenes, kölcsön alapú átigazolás",
    "kölcsönszerződés / kölcsönjáték",
    "kölcsön mozgás",
    "He completed a season-long loan move to Leeds.",
    "Egyszezonos kölcsönszerződéssel igazolt a Leedshez.",
  ],
  [
    "transfer",
    "permanent deal",
    "végleges, nem kölcsön alapú átigazolás",
    "végleges átigazolás",
    "állandó megállapodás",
    "The loan will become a permanent deal in the summer.",
    "A kölcsönből nyáron végleges átigazolás lesz.",
  ],
  [
    "transfer",
    "medical",
    "az átigazolás előtti orvosi alkalmassági vizsgálat",
    "orvosi vizsgálat",
    "orvosi (önmagában, főnévként)",
    "He passed his medical on Monday.",
    "Hétfőn sikeresen átesett az orvosi vizsgálaton.",
  ],
  [
    "transfer",
    "undisclosed fee",
    "nem nyilvánosságra hozott átigazolási összeg",
    "nem nyilvános összegért / titkos összegért",
    "fel nem fedett díj",
    "The transfer went through for an undisclosed fee.",
    "Az átigazolás nem nyilvános összegért valósult meg.",
  ],
  [
    "transfer",
    "record fee",
    "az adott klub/liga eddigi legmagasabb átigazolási díja",
    "rekordösszeg / klubrekord átigazolási díj",
    "rekorddíj",
    "It is a club-record fee for the striker.",
    "Klubrekordot jelentő összegért igazolták a csatárt.",
  ],
  [
    "transfer",
    "release clause",
    "szerződésben rögzített kivásárlási összeg",
    "kivásárlási klauzula",
    "elengedési klauzula",
    "His release clause is set at 80 million euros.",
    "Kivásárlási klauzulája 80 millió euróban van meghatározva.",
  ],
  [
    "transfer",
    "buy-back clause",
    "eladó klub jogosultsága később visszavásárolni a játékost",
    "visszavásárlási opció",
    "visszavételi klauzula",
    "The club inserted a buy-back clause into the deal.",
    "A klub visszavásárlási opciót épített be a szerződésbe.",
  ],
  [
    "transfer",
    "free transfer",
    "átigazolási díj nélküli igazolás, lejárt szerződés miatt",
    "szabad átigazolás / ingyenes igazolás",
    "ingyen transzfer",
    "He joined the club on a free transfer.",
    "Szabad átigazolással csatlakozott a klubhoz.",
  ],
  [
    "transfer",
    "free agent",
    "szerződés nélküli, bármely klubhoz igazolható játékos",
    "szabadon igazolható játékos / szabadügynök",
    "szabad ügynök (angolos írásmóddal)",
    "The veteran defender is a free agent this summer.",
    "A veterán védő ezen a nyáron szabadon igazolható.",
  ],
  [
    "transfer",
    "contract extension",
    "a meglévő szerződés meghosszabbítása",
    "szerződéshosszabbítás",
    "szerződés kiterjesztés",
    "The club confirmed his contract extension until 2028.",
    "A klub megerősítette szerződéshosszabbítását 2028-ig.",
  ],
  [
    "transfer",
    "to seal a move",
    "nyélbe ütni, lezárni egy átigazolást",
    "nyélbe üti / lezárja az átigazolást",
    "lepecsételi a lépést",
    "The midfielder is set to seal his move on Friday.",
    "A középpályás pénteken üti nyélbe az átigazolását.",
  ],
  [
    "transfer",
    "to complete a transfer",
    "hivatalossá tenni egy átigazolást",
    "hivatalossá teszi / véglegesíti az átigazolást",
    "befejezi az átigazolást",
    "The club completed the transfer on deadline day.",
    "A klub a határidő napján tette hivatalossá az átigazolást.",
  ],
  [
    "transfer",
    "sell-on clause",
    "később, továbbeladás esetén az eredeti klubnak járó részesedés",
    "továbbeladási klauzula",
    "eladási utáni klauzula",
    "The academy retains a 15% sell-on clause.",
    "Az akadémia 15%-os továbbeladási klauzulát tart fenn.",
  ],
  [
    "transfer",
    "loan with an option to buy",
    "kölcsönszerződés végleges átigazolási opcióval",
    "kölcsön vételi opcióval",
    "kölcsön vásárlási opcióval",
    "He arrived on loan with an option to buy.",
    "Kölcsönbe került, vételi opcióval.",
  ],
  [
    "transfer",
    "bid",
    "hivatalos vételi ajánlat",
    "ajánlat",
    "licit (mindig, szó szerint)",
    "The club submitted a second bid for the winger.",
    "A klub második ajánlatot nyújtott be a szélsőért.",
  ],
  [
    "transfer",
    "rejected bid",
    "visszautasított vételi ajánlat",
    "visszautasított ajánlat",
    "elutasított licit",
    "Their opening bid was rejected by the board.",
    "Nyitó ajánlatukat elutasította a klubvezetés.",
  ],
  [
    "transfer",
    "verbal agreement",
    "szóban, papír nélkül létrejött megállapodás",
    "szóbeli megállapodás",
    "verbális egyezmény",
    "The two clubs reached a verbal agreement over the fee.",
    "A két klub szóbeli megállapodásra jutott az összegről.",
  ],
  [
    "transfer",
    "here we go",
    "átigazolási hír megerősítésére utaló, ismert újságírói zsargon (Fabrizio Romano)",
    'hivatalos, megerősített hír / "megtörtént"',
    '"itt megyünk"',
    "Here we go: the deal is done and signed.",
    "Megtörtént: a szerződést aláírták, az ügylet lezárult.",
  ],
  [
    "transfer",
    "announcement",
    "a klub hivatalos közleménye egy igazolásról",
    "hivatalos bejelentés",
    "announszmentum / kihirdetés",
    "The official announcement is expected on Monday.",
    "A hivatalos bejelentés hétfőn várható.",
  ],
  [
    "transfer",
    "unveiling",
    "az új igazolás nyilvános bemutatása szurkolóknak/sajtónak",
    "bemutatása (a klub részéről)",
    "leleplezés",
    "The club held the player's unveiling at the stadium.",
    "A klub a stadionban tartotta az új igazolás bemutatását.",
  ],
  [
    "transfer",
    "marquee signing",
    "a szurkolókat/médiát leginkább vonzó, húzónévnek számító igazolás",
    "húzónévnek számító igazolás",
    "márkás aláírás",
    "The World Cup winner is their marquee signing this summer.",
    "A világbajnok a klub húzónévnek számító nyári igazolása.",
  ],
  [
    "transfer",
    "swap deal",
    "két játékos cseréjén alapuló átigazolási konstrukció",
    "cserebiznisz / játékoscsere-üzlet",
    "csere-ügylet",
    "The clubs are discussing a potential swap deal.",
    "A klubok egy lehetséges cserebizniszről tárgyalnak.",
  ],
  [
    "transfer",
    "player-plus-cash deal",
    "játékos és készpénz kombinációjából álló átigazolási konstrukció",
    "játékos plusz készpénz konstrukció",
    "játékos-plusz-pénz üzlet",
    "The move could be structured as a player-plus-cash deal.",
    "Az átigazolás egy játékos plusz készpénz konstrukcióban valósulhat meg.",
  ],
  [
    "transfer",
    "release from contract",
    "a szerződés közös megegyezéssel vagy egyoldalúan történő felbontása",
    "kiengedik/felbontják a szerződését",
    "kiengedés a szerződésből",
    "The club agreed to release him from his contract.",
    "A klub beleegyezett szerződése felbontásába.",
  ],
  [
    "transfer",
    "mutual consent",
    "mindkét fél egyetértésével történő szerződésbontás",
    "közös megegyezés",
    "kölcsönös beleegyezés",
    "The contract was terminated by mutual consent.",
    "A szerződést közös megegyezéssel bontották fel.",
  ],
  [
    "transfer",
    "red-hot favourite",
    "esélyesként emlegetett jelölt egy igazolásra",
    "esélyes jelölt",
    "vörös-forró esélyes",
    "He is the red-hot favourite to sign for the champions.",
    "Ő a bajnokcsapat igazolásának legesélyesebb jelöltje.",
  ],
  [
    "transfer",
    "chase a target",
    "aktívan törekedni egy kiszemelt játékos leigazolására",
    "hajt egy igazolásért / kiszemel egy játékost",
    "üldöz egy célpontot",
    "The club has been chasing the target for months.",
    "A klub hónapok óta hajt a kiszemelt játékos leigazolásáért.",
  ],
  [
    "transfer",
    "long-term target",
    "régóta figyelt, kiszemelt igazolási célpont",
    "régóta kiszemelt játékos",
    "hosszú távú célpont",
    "The striker has been a long-term target for the manager.",
    "A csatár régóta a vezetőedző kiszemelt célpontja.",
  ],
  [
    "transfer",
    "head scout",
    "a klub megfigyelői stábjának vezetője",
    "főmegfigyelő",
    "fő scout",
    "The head scout recommended the young defender.",
    "A főmegfigyelő ajánlotta a fiatal védőt.",
  ],
  [
    "transfer",
    "scouting report",
    "megfigyelő által készített értékelő jelentés egy játékosról",
    "megfigyelői jelentés",
    "scoutolási riport",
    "The scouting report praised his positioning.",
    "A megfigyelői jelentés kiemelte a helyezkedését.",
  ],
  [
    "transfer",
    "due diligence",
    "az átigazolás előtti alapos háttér-átvilágítás",
    "átvilágítás / alapos vizsgálat",
    "kellő gondosság",
    "The club carried out due diligence before the deal.",
    "A klub alapos átvilágítást végzett az üzlet előtt.",
  ],
  [
    "transfer",
    "agent",
    "a játékos érdekeit képviselő szakmai közvetítő",
    "menedzser / ügynök",
    "agent (angolos formában)",
    "His agent confirmed the talks are ongoing.",
    "Menedzsere megerősítette, hogy folynak a tárgyalások.",
  ],
  [
    "transfer",
    "put pen to paper",
    "aláírni a szerződést",
    "aláírja a szerződést",
    "tollat papírra tesz",
    "He is expected to put pen to paper this week.",
    "Várhatóan ezen a héten aláírja a szerződést.",
  ],
  [
    "transfer",
    "sign on the dotted line",
    "hivatalosan aláírni egy szerződést",
    "aláírja a papírokat / hivatalossá teszi az igazolást",
    "aláír a pontozott vonalon",
    "The winger signed on the dotted line on Thursday.",
    "A szélső csütörtökön aláírta a szerződését.",
  ],
  [
    "transfer",
    "gazump",
    "egy már majdnem lezárt ajánlatot túllicitálni",
    "túllicitál egy ajánlatot",
    "gazumpol",
    "A rival club tried to gazump the deal at the last minute.",
    "Egy rivális klub az utolsó pillanatban próbálta túllicitálni az ajánlatot.",
  ],
  [
    "transfer",
    "hijack a transfer",
    "más klub elől, váratlanul elcsípni egy átigazolást",
    "elcsíp egy igazolást (más klub elől)",
    "eltéríti az átigazolást",
    "They hijacked the transfer with a higher bid.",
    "Magasabb ajánlattal csípték el az igazolást a rivális elől.",
  ],
  [
    "transfer",
    "gentleman's agreement",
    "íratlan, becsületbeli megállapodás",
    "úriemberi megállapodás",
    "úriember-egyezmény",
    "There was a gentleman's agreement over the release clause.",
    "Úriemberi megállapodás született a kivásárlási klauzuláról.",
  ],
  [
    "transfer",
    "transfer embargo",
    "hivatalos tiltás, amely megakadályozza a klub igazolásait",
    "átigazolási tilalom",
    "átigazolási embargó (kerülendő, ha van jobb magyar forma)",
    "The club is unable to sign anyone due to a transfer embargo.",
    "A klub az átigazolási tilalom miatt senkit sem tud leigazolni.",
  ],
  [
    "transfer",
    "FFP breach",
    "a pénzügyi fair play szabályainak megsértése",
    "pénzügyi fair play szabály megsértése",
    "FFP törés",
    "The club was fined for an FFP breach.",
    "A klubot megbírságolták a pénzügyi fair play szabály megsértése miatt.",
  ],
  [
    "transfer",
    "loan return",
    "visszatérés a kölcsönjátékból az anyaklubhoz",
    "visszatér a kölcsönből",
    "kölcsön-visszatérés",
    "He is expected back at the club after his loan return.",
    "Kölcsönjátéka után várhatóan visszatér a klubhoz.",
  ],
  [
    "transfer",
    "recall from loan",
    "az anyaklub idő előtt visszahívja a kölcsönben lévő játékost",
    "visszahívja a kölcsönből",
    "visszahívás kölcsönről",
    "The club recalled him from loan in January.",
    "A klub januárban visszahívta a kölcsönből.",
  ],
  [
    "transfer",
    "co-ownership",
    "két klub közötti, régi (főleg olasz) közös tulajdonlási forma",
    "társtulajdonlás",
    "ko-tulajdonlás",
    "The two Italian clubs agreed a co-ownership deal.",
    "A két olasz klub társtulajdonlási megállapodásra jutott.",
  ],
  [
    "transfer",
    "buyout clause",
    "meghatározott, fix összegű kivásárlási feltétel",
    "kivásárlási záradék",
    "kivásárlási klauzula (ld. release clause, ha megkülönböztetés kell)",
    "His buyout clause activates only in the summer window.",
    "Kivásárlási záradéka csak a nyári átigazolási időszakban aktiválható.",
  ],
  [
    "transfer",
    "contract rebel",
    "szerződését, klubját nyíltan elutasító, lázadó játékos",
    "szerződését megtagadó játékos",
    "szerződés-lázadó",
    "The contract rebel refused to train with the squad.",
    "A szerződését megtagadó játékos megtagadta a csapattal való edzést.",
  ],
  [
    "transfer",
    "transfer request",
    "hivatalos kérelem az átigazolás engedélyezésére",
    "átigazolási kérelem",
    "transzferkérés",
    "He submitted a transfer request in the summer.",
    "Nyáron átigazolási kérelmet nyújtott be.",
  ],
  [
    "transfer",
    "want-away player",
    "a klubtól távozni kívánó játékos",
    "távozni vágyó játékos",
    "el akar menni játékos",
    "The want-away player trained separately from the group.",
    "A távozni vágyó játékos külön edzett a csapattól.",
  ],
  [
    "transfer",
    "homegrown player",
    "a klub saját akadémiáján nevelkedett játékos",
    "hazai nevelésű játékos",
    "otthon nevelt játékos",
    "The rules require a minimum number of homegrown players.",
    "A szabályzat minimum számú hazai nevelésű játékost ír elő.",
  ],
  [
    "transfer",
    "marquee free agent",
    "nagy névértékű, szerződés nélküli sztárjátékos",
    "nagynevű szabadügynök",
    "márkás szabad ügynök",
    "The marquee free agent is attracting interest from three clubs.",
    "A nagynevű szabadügynök három klub érdeklődését kelti fel.",
  ],
  [
    "transfer",
    "advanced talks",
    "a végső fázisban lévő átigazolási tárgyalások",
    "előrehaladott tárgyalások",
    "haladó tárgyalások",
    "The two parties are in advanced talks over a fee.",
    "A felek előrehaladott tárgyalásokat folytatnak az összegről.",
  ],
  [
    "transfer",
    "imminent",
    "hamarosan, küszöbön álló esemény (átigazolásra utalva)",
    "küszöbön áll",
    "imminens",
    "His move to the capital is imminent.",
    "Fővárosi átigazolása küszöbön áll.",
  ],
  [
    "transfer",
    "medical passed",
    "sikeresen teljesített orvosi alkalmassági vizsgálat",
    "sikeres orvosi vizsgálat",
    "átment az orvosin",
    "The medical was passed without any issues.",
    "Az orvosi vizsgálaton mindenféle probléma nélkül átment.",
  ],
  [
    "transfer",
    "pre-contract agreement",
    "jövőbeli, ingyenes átigazolást előkészítő szerződés",
    "előszerződés",
    "előzetes szerződéses megállapodás",
    "He signed a pre-contract agreement in January.",
    "Januárban előszerződést írt alá.",
  ],
  [
    "transfer",
    "loan fee",
    "a kölcsönszerződésért fizetett díj",
    "kölcsöndíj",
    "kölcsönzési díj",
    "The club paid a loan fee of two million euros.",
    "A klub kétmillió eurós kölcsöndíjat fizetett.",
  ],
  [
    "transfer",
    "buy option",
    "opció a kölcsönjáték végén a végleges átigazolásra",
    "vételi opció",
    "vásárlási opció",
    "The deal includes a mandatory buy option.",
    "Az üzlet kötelező vételi opciót tartalmaz.",
  ],
  [
    "transfer",
    "shirt number reveal",
    "az új igazolás mezszámának bejelentése",
    "mezszám-bejelentés",
    "mez szám leleplezés",
    "The club confirmed his shirt number reveal for Friday.",
    "A klub megerősítette, hogy pénteken jelentik be mezszámát.",
  ],

  // ---------------------------------------------------------------------
  // MÉRKŐZÉSBESZÁMOLÓK (match_report)
  // ---------------------------------------------------------------------
  [
    "match_report",
    "full-time",
    "a mérkőzés lefújásának pillanata / a végeredmény",
    "a mérkőzés vége / a végeredmény szerint",
    "teljes idő",
    "Full-time: the hosts win 2-1.",
    "A mérkőzés végén a hazaiak nyertek 2-1-re.",
  ],
  [
    "match_report",
    "half-time",
    "az első félidő vége",
    "félidő",
    "fél idő (két szóban)",
    "It was 1-0 at half-time.",
    "Félidőben 1-0 volt az állás.",
  ],
  [
    "match_report",
    "stoppage time",
    "a játékvezető által hozzáadott hosszabbítás",
    "hosszabbítás / ráadás",
    "megállási idő",
    "The winner came in stoppage time.",
    "A győztes gól a hosszabbításban esett.",
  ],
  [
    "match_report",
    "injury time",
    "sérülések miatt hozzáadott játékidő",
    "sérülés miatti hosszabbítás / ráadás",
    "sérülési idő",
    "Three minutes of injury time were added.",
    "Három perc sérülés miatti hosszabbítást adott hozzá a bíró.",
  ],
  [
    "match_report",
    "extra time",
    "a rendes játékidő utáni, kieséses meccseken alkalmazott hosszabbítás",
    "hosszabbítás (a rendes idő után)",
    "extra idő",
    "The match went to extra time after a 1-1 draw.",
    "1-1-es döntetlen után a mérkőzés hosszabbításra ment.",
  ],
  [
    "match_report",
    "penalty shootout",
    "extra idő után tizenegyesekkel eldöntött végeredmény",
    "tizenegyespárbaj",
    "büntető lövöldözés",
    "They won the penalty shootout 5-4.",
    "A tizenegyespárbajt 5-4-re nyerték.",
  ],
  [
    "match_report",
    "clean sheet",
    "gól nélkül lezárt mérkőzés a védekező csapat szemszögéből",
    "kapott gól nélkül zárta a meccset",
    "tiszta lap",
    "The goalkeeper kept a clean sheet in his debut.",
    "A kapus bemutatkozásán kapott gól nélkül zárt.",
  ],
  [
    "match_report",
    "brace",
    "két gól egy mérkőzésen ugyanattól a játékostól",
    "duplázás / két gólos teljesítmény",
    "karkötő / kar",
    "He scored a brace in the first half.",
    "Az első félidőben duplázott.",
  ],
  [
    "match_report",
    "hat-trick",
    "három gól egy mérkőzésen ugyanattól a játékostól",
    "mesterhármas",
    "kalaptrükk (szó szerint, kerülendő)",
    "The striker completed his hat-trick with a penalty.",
    "A csatár egy tizenegyessel fejezte be a mesterhármasát.",
  ],
  [
    "match_report",
    "own goal",
    "a saját kapuba lőtt gól",
    "öngól",
    "saját gól",
    "The defender's own goal proved decisive.",
    "A védő öngólja bizonyult döntőnek.",
  ],
  [
    "match_report",
    "equaliser",
    "az állást kiegyenlítő gól",
    "egyenlítő gól",
    "kiegyenlítő (főnévként, önmagában furcsa)",
    "He netted a late equaliser.",
    "Késői egyenlítő gólt szerzett.",
  ],
  [
    "match_report",
    "winner (goal)",
    "a mérkőzést eldöntő gól",
    "győztes gól",
    "nyerő gól",
    "The winner came five minutes from time.",
    "A győztes gól öt perccel a vége előtt esett.",
  ],
  [
    "match_report",
    "late winner",
    "a mérkőzés végén, hajrában szerzett győztes gól",
    "késői győztes gól",
    "kései nyerő",
    "A late winner sealed the three points.",
    "Egy késői győztes gól biztosította a három pontot.",
  ],
  [
    "match_report",
    "consolation goal",
    "vereség esetén, csupán az eredményt szépítő gól",
    "szépítő gól",
    "vigasz gól",
    "The consolation goal came too late to matter.",
    "A szépítő gól már túl későn esett ahhoz, hogy számítson.",
  ],
  [
    "match_report",
    "rout",
    "kiütéses, egyoldalú győzelem",
    "kiütéses győzelem",
    "menekülés",
    "It was a rout: 6-0 to the visitors.",
    "Kiütéses győzelmet aratott a vendégcsapat, 6-0-ra.",
  ],
  [
    "match_report",
    "comeback",
    "hátrányból kikászálódó, fordítást elérő teljesítmény",
    "fordítás",
    "visszatérés",
    "They staged a stunning comeback from 2-0 down.",
    "Elképesztő fordítást hajtottak végre 2-0-s hátrányból.",
  ],
  [
    "match_report",
    "nervy finish",
    "feszült, idegtépő végjáték",
    "idegtépő hajrá",
    "ideges befejezés",
    "It was a nervy finish for the home fans.",
    "Idegtépő hajrát kaptak a hazai szurkolók.",
  ],
  [
    "match_report",
    "narrow win",
    "kis különbséggel elért győzelem",
    "szoros győzelem",
    "keskeny győzelem",
    "A narrow win keeps them in the title race.",
    "A szoros győzelem életben tartja a bajnoki esélyeiket.",
  ],
  [
    "match_report",
    "dominant display",
    "fölényes, uraló teljesítmény",
    "fölényes teljesítmény / játék",
    "domináns megjelenés",
    "It was a dominant display from start to finish.",
    "Elejétől a végéig fölényes teljesítményt nyújtottak.",
  ],
  [
    "match_report",
    "one-sided affair",
    "egyoldalú, kiegyenlítetlen mérkőzés",
    "egyoldalú mérkőzés",
    "egyoldalú ügy",
    "The final proved a one-sided affair.",
    "A döntő egyoldalú mérkőzésnek bizonyult.",
  ],
  [
    "match_report",
    "goalless draw",
    "gól nélküli döntetlen",
    "gól nélküli döntetlen",
    'gól nélküli döntő (vigyázat: "döntő" félrefordítás!)',
    "The two sides played out a goalless draw.",
    "A két csapat gól nélküli döntetlent játszott.",
  ],
  [
    "match_report",
    "share the points",
    "mindkét csapat egy-egy pontot szerez döntetlennel",
    "osztozik a pontokon",
    "megosztja a pontokat",
    "The teams shared the points after a 1-1 draw.",
    "A csapatok 1-1 után osztoztak a pontokon.",
  ],
  [
    "match_report",
    "drop points",
    "várt győzelem helyett pontot/pontokat veszíteni",
    "pontot/pontokat veszít",
    "leejti a pontokat",
    "They dropped points against the bottom side.",
    "Pontokat veszítettek a tabella utolsó helyezettje ellen.",
  ],
  [
    "match_report",
    "snatch a point",
    "váratlanul, az utolsó pillanatban pontot menteni",
    "pontot ment",
    "elcsíp egy pontot",
    "They snatched a point in the dying seconds.",
    "Az utolsó másodpercekben pontot mentettek.",
  ],
  [
    "match_report",
    "kick-off",
    "a mérkőzés kezdő rúgása / kezdési időpontja",
    "kezdőrúgás / kezdés",
    "rúgás elindítás",
    "Kick-off is scheduled for 6pm.",
    "A kezdés 18 órára van kitűzve.",
  ],
  [
    "match_report",
    "final whistle",
    "a játékvezető záró sípszava",
    "végső sípszó / a mérkőzés vége",
    "utolsó síp",
    "The final whistle brought huge relief for the hosts.",
    "A végső sípszó óriási megkönnyebbülést hozott a hazaiaknak.",
  ],
  [
    "match_report",
    "matchwinner",
    "a mérkőzést eldöntő gólt szerző/teljesítményt nyújtó játékos",
    "mérkőzést eldöntő játékos",
    "meccs-nyerő",
    "The substitute proved the matchwinner.",
    "A csereként beálló játékos bizonyult a mérkőzést eldöntőnek.",
  ],
  [
    "match_report",
    "man of the match",
    "a mérkőzés legjobbjának választott játékos",
    "a mérkőzés embere / a meccs legjobbja",
    "az ember a meccsből",
    "He was named man of the match after two assists.",
    "Két gólpassza után a mérkőzés emberének választották.",
  ],
  [
    "match_report",
    "capacity crowd",
    "telt házas, tele stadiont jelentő nézőszám",
    "telt ház",
    "kapacitás tömeg",
    "A capacity crowd packed the stadium.",
    "Telt ház előtt rendezték a mérkőzést.",
  ],
  [
    "match_report",
    "attendance",
    "a mérkőzésen jelen lévő nézők száma",
    "nézőszám",
    "attendancia (kerülendő anglicizmus)",
    "The attendance was just over 40,000.",
    "A nézőszám alig haladta meg a 40 ezret.",
  ],
  [
    "match_report",
    "away day",
    "idegenbeli mérkőzésre utazás, szurkolói élmény",
    "idegenbeli mérkőzés / kiruccanás",
    "távoli nap",
    "It was a long away day for the travelling fans.",
    "Hosszú kiruccanás volt ez az utazó szurkolóknak.",
  ],
  [
    "match_report",
    "derby day",
    "helyi rangadó napja",
    "rangadó napja",
    "derbi nap",
    "Derby day always brings extra intensity.",
    "A rangadó napja mindig extra intenzitást hoz.",
  ],
  [
    "match_report",
    "six-pointer",
    "két közvetlen riválisnak kiemelten fontos, hatpontos jelentőségű mérkőzés",
    "hatpontos meccs / kulcsfontosságú párharc",
    "hat pontos meccs (szó szerint furcsa)",
    "This is a genuine six-pointer at the bottom of the table.",
    "Ez valódi hatpontos meccs a tabella alján.",
  ],
  [
    "match_report",
    "dead rubber",
    "olyan mérkőzés, aminek eredménye már nem befolyásol semmit",
    "tétnélküli mérkőzés",
    "halott gumi",
    "The final group game was a dead rubber for both sides.",
    "A csoport utolsó fordulója mindkét csapat számára tétnélküli volt.",
  ],
  [
    "match_report",
    "banana skin",
    "papírformán könnyűnek tűnő, mégis veszélyes ellenfél/mérkőzés",
    "buktató",
    "banánhéj",
    "The cup tie is a potential banana skin.",
    "A kupamérkőzés lehetséges buktató.",
  ],
  [
    "match_report",
    "giant-killing",
    "esélytelen csapat váratlan győzelme egy sokkal erősebb ellen",
    "bravúrgyőzelem esélytelenből",
    "óriásölés",
    "It was one of the great giant-killings in cup history.",
    "A kupa történetének egyik legnagyobb bravúrgyőzelme volt.",
  ],
  [
    "match_report",
    "cup upset",
    "meglepetést hozó kupaeredmény",
    "kupameglepetés",
    "kupa felfordulás",
    "The lower-league side pulled off a cup upset.",
    "Az alacsonyabb osztályú csapat kupameglepetést okozott.",
  ],
  [
    "match_report",
    "replay",
    "kupamérkőzés újrajátszása döntetlen után",
    "újrajátszás",
    "visszajátszás (kerülendő, mert máshol mást jelent)",
    "The tie will be settled in a replay.",
    "A párharcot egy újrajátszás dönti el.",
  ],
  [
    "match_report",
    "game management",
    "a megszerzett előny tudatos megőrzése a mérkőzés hátralévő részében",
    "mérkőzésvezetés / a meccs kézben tartása",
    "játékmenedzsment",
    "Their game management in the closing minutes was excellent.",
    "A záró percekben kiválóan tartották kézben a mérkőzést.",
  ],
  [
    "match_report",
    "see out the game",
    "sikeresen levezetni, lehozni a mérkőzés hátralévő részét",
    "kimenekíti / lehozza a meccset",
    "kilátja a játékot",
    "They saw out the game comfortably.",
    "Magabiztosan hozták le a mérkőzés hátralévő részét.",
  ],
  [
    "match_report",
    "put the game to bed",
    "biztossá tenni a győzelmet egy további góllal",
    "eldönti a mérkőzést",
    "ágyba teszi a meccset",
    "The third goal put the game to bed.",
    "A harmadik gól eldöntötte a mérkőzést.",
  ],
  [
    "match_report",
    "rescue a point",
    "hátrányból, a hajrában pontot menteni",
    "pontot ment",
    "megmenti a pontot",
    "A last-minute penalty rescued a point.",
    "Egy tizenegyesből mentett pontot a hajrában.",
  ],
  [
    "match_report",
    "squander a lead",
    "megszerzett előnyt elpazarolni",
    "elpazarolja az előnyt",
    "eldobja a vezetést (ld. blow a lead)",
    "They squandered a two-goal lead.",
    "Elpazarolták kétgólos előnyüket.",
  ],
  [
    "match_report",
    "blow a lead",
    "megszerzett előnyt elveszíteni",
    "eldobja a vezetést",
    "elfújja a vezetést",
    "The team blew a 3-0 lead to draw 3-3.",
    "A csapat eldobta 3-0-s vezetését, és 3-3-ra végzett.",
  ],
  [
    "match_report",
    "VAR check",
    "a videóbírói rendszer általi ellenőrzés",
    "videóbírói vizsgálat",
    "VAR ellenőrzés (angolos rövidítéssel is elfogadott)",
    "The goal stood after a lengthy VAR check.",
    "A gólt egy hosszú videóbírói vizsgálat után is megadták.",
  ],
  [
    "match_report",
    "overturned by VAR",
    "a videóbíró által megváltoztatott bírói döntés",
    "videóbíró felülbírálta",
    "megfordítva a VAR által",
    "The penalty was overturned by VAR.",
    "A tizenegyest a videóbíró felülbírálta.",
  ],
  [
    "match_report",
    "offside flag",
    "a partjelző lesre utaló jelzése",
    "lesjelzés",
    "les zászló",
    "The offside flag was raised immediately.",
    "A partjelző azonnal jelezte a lest.",
  ],
  [
    "match_report",
    "marginal offside",
    "alig érzékelhető, centiméteres lesállás",
    "centiméteres les",
    "marginális les",
    "It was a marginal offside call.",
    "Centiméteres les miatt fújták le a gólt.",
  ],
  [
    "match_report",
    "reviewed decision",
    "videóbíró által felülvizsgált bírói döntés",
    "felülvizsgált döntés",
    "átnézett döntés",
    "The reviewed decision favoured the home side.",
    "A felülvizsgált döntés a hazaiaknak kedvezett.",
  ],

  // ---------------------------------------------------------------------
  // TAKTIKAI KIFEJEZÉSEK (tactics)
  // ---------------------------------------------------------------------
  [
    "tactics",
    "false nine",
    "mélyre húzódó, klasszikus center helyett kötött szerepű csatár",
    "hamis kilences",
    "hamis kilenc",
    "He operates as a false nine in this system.",
    "Hamis kilencesként szerepel ebben a rendszerben.",
  ],
  [
    "tactics",
    "high press",
    "magasan, az ellenfél térfelén kezdeményezett letámadás",
    "magas letámadás",
    "magas nyomás (túl szó szerinti)",
    "Their high press forced several turnovers.",
    "Magas letámadásukkal több labdaszerzést is kikényszerítettek.",
  ],
  [
    "tactics",
    "gegenpressing",
    "labdavesztés utáni azonnali, agresszív letámadás",
    "kontrapresszing",
    "gegenpresszingelés (kerülendő ragozás)",
    "Gegenpressing is the cornerstone of his tactics.",
    "A kontrapresszing a taktikájának alapköve.",
  ],
  [
    "tactics",
    "low block",
    "mélyen, saját kapu közelében felálló, tömör védekezés",
    "mélyre húzódó védekezés",
    "alacsony blokk",
    "They set up in a low block for the entire match.",
    "Az egész mérkőzésen mélyre húzódó védekezést alkalmaztak.",
  ],
  [
    "tactics",
    "counter-attack",
    "labdaszerzés utáni gyors, ellentámadás jellegű akció",
    "kontratámadás",
    "ellen-támadás",
    "The winning goal came on the counter-attack.",
    "A győztes gól egy kontratámadásból esett.",
  ],
  [
    "tactics",
    "build-up play",
    "hátulról, tudatosan felépített, kombinatív játék",
    "felépített játék",
    "felépítési játék",
    "Their build-up play was patient and controlled.",
    "Türelmes, kontrollált felépített játékot mutattak be.",
  ],
  [
    "tactics",
    "overlapping run",
    "a szélső mellett/mögötte kívülről előretörő futás",
    "átfutás (a szélső mellett)",
    "átfedő futás",
    "The full-back made an overlapping run down the flank.",
    "A hátvéd átfutott a szélső mellett a szélen.",
  ],
  [
    "tactics",
    "underlapping run",
    "a szélső belső íven, a védelem és a szélső között előretörő futás",
    "belső ívű átfutás",
    "alul-futás",
    "He timed his underlapping run perfectly.",
    "Tökéletesen időzítette a belső ívű átfutását.",
  ],
  [
    "tactics",
    "inverted winger",
    "domináns lábával ellentétes oldalon játszó szélső",
    "fordított lábas szélső",
    "megfordított szélső",
    "The inverted winger cuts inside onto his stronger foot.",
    "A fordított lábas szélső befelé húzódik erősebb lábára.",
  ],
  [
    "tactics",
    "wing-back",
    "támadásban és védekezésben is aktív, a teljes szélt bejáró hátvéd",
    "szélsőhátvéd",
    "szárny-hátvéd",
    "The wing-back provides width in attack.",
    "A szélsőhátvéd biztosítja a szélességet a támadásban.",
  ],
  [
    "tactics",
    "double pivot",
    "két, mélyen felépítő középpályásból álló középpályás páros",
    "dupla védekező középpályás pár",
    "dupla pivot",
    "The double pivot shields the back four.",
    "A dupla védekező középpályás páros védi a négyes védősort.",
  ],
  [
    "tactics",
    "holding midfielder",
    "elsősorban védekező feladatokat ellátó középpályás",
    "védekező középpályás",
    "tartó középpályás",
    "The holding midfielder broke up several attacks.",
    "A védekező középpályás több támadást is megszakított.",
  ],
  [
    "tactics",
    "box-to-box midfielder",
    "mindkét kapu előtt aktív, a teljes pályát bejáró középpályás",
    "box-to-box középpályás / mindenes középpályás",
    "doboztól-dobozig középpályás",
    "He is a classic box-to-box midfielder.",
    "Klasszikus box-to-box középpályás típus.",
  ],
  [
    "tactics",
    "target man",
    "fizikai erejére és fejjátékára építő, hosszú labdákat megtartó csatár",
    "céltámadó",
    "célember",
    "The target man held up the ball well.",
    "A céltámadó jól tartotta meg a labdát.",
  ],
  [
    "tactics",
    "poacher",
    "a tizenhatoson belül helyezkedő, gólérzékeny csatártípus",
    "gólvadász",
    "orvvadász (szó szerint helytelen konnotáció)",
    "He is a natural poacher inside the box.",
    "A tizenhatoson belül ösztönös gólvadász.",
  ],
  [
    "tactics",
    "deep-lying playmaker",
    "mélyről irányító, a támadásokat felépítő középpályás",
    "hátrahúzott irányító",
    "mélyen fekvő játékkészítő",
    "The deep-lying playmaker dictated the tempo.",
    "A hátrahúzott irányító diktálta az iramot.",
  ],
  [
    "tactics",
    "attacking midfielder",
    "a támadósor mögött, kreatív feladatokat ellátó középpályás",
    "támadó középpályás",
    "attakoló középpályás",
    "The attacking midfielder set up both goals.",
    "A támadó középpályás mindkét gólt előkészítette.",
  ],
  [
    "tactics",
    "width",
    "a pálya szélességének kihasználása a támadásban",
    "szélesség (kihasználása)",
    "szélesség (szó szerint, kontextus nélkül furcsa)",
    "The wingers provide great width to the attack.",
    "A szélsők remekül kihasználják a pálya szélességét.",
  ],
  [
    "tactics",
    "compact shape",
    "szorosan, kis térben tartott csapatalakzat",
    "kompakt alakzat",
    "kompakt forma",
    "They kept a compact shape without the ball.",
    "Labda nélkül kompakt alakzatot tartottak.",
  ],
  [
    "tactics",
    "defensive line",
    "a védők által alkotott vonal magassága",
    "védősor / védelmi vonal",
    "defenzív vonal",
    "The defensive line pushed up to press.",
    "A védősor feljebb tolódott a letámadáshoz.",
  ],
  [
    "tactics",
    "offside trap",
    "a védősor szándékos, összehangolt előrelépése lest kiváltva",
    "lescsapda",
    "les csapda",
    "The offside trap failed twice in the first half.",
    "A lescsapda kétszer is bevallott az első félidőben.",
  ],
  [
    "tactics",
    "zonal marking",
    "a pálya adott zónájáért, nem meghatározott játékosért felelős védekezés",
    "zónázás / zónavédekezés",
    "zonális jelölés",
    "They use zonal marking at set pieces.",
    "Álló helyzeteknél zónázást alkalmaznak.",
  ],
  [
    "tactics",
    "man-marking",
    "egy adott ellenfél kizárólagos, szoros követése",
    "emberfogás",
    "ember-jelölés",
    "He was given the man-marking job on the playmaker.",
    "Az irányító emberfogását bízták rá.",
  ],
  [
    "tactics",
    "through ball",
    "a védősor mögé, a támadó elé juttatott passz",
    "bedobó labda / a védelem mögé küldött passz",
    "át-labda",
    "The through ball split the defence perfectly.",
    "A bedobó labda tökéletesen kettévágta a védelmet.",
  ],
  [
    "tactics",
    "cutback",
    "az alapvonal közeléből hátra, a tizenhatos elé visszagurított labda",
    "visszagurítás",
    "vissza-vágás",
    "The cutback found the striker unmarked.",
    "A visszagurítás üresen találta a csatárt.",
  ],
  [
    "tactics",
    "switch of play",
    "a labda gyors átjuttatása a pálya egyik oldaláról a másikra",
    "oldalváltás",
    "játékváltás",
    "The switch of play caught the defence off guard.",
    "Az oldalváltás felkészületlenül érte a védelmet.",
  ],
  [
    "tactics",
    "one-two",
    "két játékos közötti gyors passzcsel",
    "passzcsel / adok-kapok",
    "egy-kettő",
    "They combined with a slick one-two.",
    "Egy gördülékeny passzcsellel kombináltak.",
  ],
  [
    "tactics",
    "overload",
    "számszerű emberelőny kialakítása egy adott zónában",
    "emberelőny kialakítása (egy zónában)",
    "túlterhelés",
    "They created an overload on the right flank.",
    "Emberelőnyt alakítottak ki a jobb szélen.",
  ],
  [
    "tactics",
    "isolate a defender",
    "egy védőt szándékosan egy az egyben helyzetbe hozni",
    "egy az egyben helyzetbe hoz egy védőt",
    "elszigetel egy védőt",
    "The winger isolated his marker one-on-one.",
    "A szélső egy az egyben helyzetbe hozta emberét.",
  ],
  [
    "tactics",
    "press trigger",
    "a letámadás megindítását kiváltó jel/pillanat",
    "letámadási jel",
    "nyomás trigger",
    "A poor first touch was the press trigger.",
    "A gyenge labdaátvétel volt a letámadás jele.",
  ],
  [
    "tactics",
    "transition",
    "a támadásból védekezésbe (vagy fordítva) váltás pillanata",
    "játékfázisváltás",
    "átmenet",
    "They were vulnerable in transition.",
    "Játékfázisváltáskor sebezhetőek voltak.",
  ],
  [
    "tactics",
    "rest defense",
    "a támadás közben hátrahagyott, biztosító játékosok elrendezése",
    "védekező biztosítás (támadás közben)",
    "pihenő védelem",
    "Their rest defense left them exposed to counters.",
    "Védekező biztosításuk kiszolgáltatottá tette őket a kontráknak.",
  ],
  [
    "tactics",
    "back three",
    "három középhátvédből álló védelmi rendszer",
    "hármas védelem / hárompótos védősor",
    "hátsó három",
    "They switched to a back three at half-time.",
    "Félidőben hármas védelemre váltottak.",
  ],
  [
    "tactics",
    "wing play",
    "a szélső sávok kihasználására épülő játékstílus",
    "szélső játék",
    "szárny-játék",
    "Their wing play created most of the chances.",
    "A szélső játékukból született a legtöbb helyzet.",
  ],
  [
    "tactics",
    "narrow formation",
    "szűkített, a középső sávra koncentráló alakzat",
    "szűkített alakzat",
    "keskeny formáció",
    "They lined up in a narrow formation.",
    "Szűkített alakzatban álltak fel.",
  ],
  [
    "tactics",
    "positional play",
    "a pálya adott zónáinak tudatos, pozíció alapú kihasználására épülő játékfelfogás",
    "pozíciójáték",
    "pozicionális játék",
    "Positional play is central to his footballing philosophy.",
    "A pozíciójáték áll futballfilozófiája középpontjában.",
  ],
  [
    "tactics",
    "half-space",
    "a szélső sáv és a középső folyosó közötti taktikai zóna",
    "félterek",
    "fél-tér",
    "He thrives operating in the half-spaces.",
    "A félterekben mozogva érzi igazán jól magát.",
  ],
  [
    "tactics",
    "pressing trap",
    "a letámadás tudatosan egy irányba tereli az ellenfelet, majd elveszi a labdát",
    "letámadási csapda",
    "nyomási csapda",
    "They lured them into a pressing trap.",
    "Letámadási csapdába csalták az ellenfelet.",
  ],
  [
    "tactics",
    "counter-press",
    "labdavesztés utáni azonnali, néhány másodperces letámadás",
    "azonnali letámadás (labdavesztés után)",
    "ellen-nyomás",
    "Their counter-press won the ball back within seconds.",
    "Azonnali letámadásukkal másodperceken belül visszaszerezték a labdát.",
  ],
  [
    "tactics",
    "game state",
    "a mérkőzés aktuális állása, ami befolyásolja a taktikai döntéseket",
    "mérkőzésállás (taktikai értelemben)",
    "játék állapot",
    "The game state forced them to attack more.",
    "A mérkőzésállás támadóbb játékra kényszerítette őket.",
  ],
  [
    "tactics",
    "formation switch",
    "a csapat alakzatának menet közbeni megváltoztatása",
    "alakzatváltás",
    "formáció csere",
    "The formation switch changed the game completely.",
    "Az alakzatváltás teljesen megváltoztatta a mérkőzést.",
  ],
  [
    "tactics",
    "plan B",
    "az elsődleges taktikától eltérő, tartalék játékterv",
    '"B terv" / alternatív taktika',
    "B terv (szó szerint is elfogadható, de context kell)",
    "The manager had no plan B when the press failed.",
    "A vezetőedzőnek nem volt B terve, amikor a letámadás nem működött.",
  ],
  [
    "tactics",
    "tempo control",
    "a mérkőzés iramának tudatos szabályozása",
    "iramkontroll",
    "tempó kontroll",
    "Their midfield dictated tempo control all game.",
    "Középpályájuk az egész meccsen kontrollálta az iramot.",
  ],
  [
    "tactics",
    "build from the back",
    "a védősorból, kapustól induló, kombinatív felépítés",
    "hátulról felépített játék",
    "hátulról építkezés",
    "They like to build from the back under pressure.",
    "Nyomás alatt is szeretnek hátulról felépíteni.",
  ],
  [
    "tactics",
    "long-ball tactic",
    "a rövid passzjáték mellőzésével, hosszú labdákra épülő taktika",
    "hosszúlabdás taktika",
    "hosszú-labda taktika",
    "They resorted to a long-ball tactic in the second half.",
    "A második félidőben hosszúlabdás taktikára váltottak.",
  ],
  [
    "tactics",
    "set-piece routine",
    "előre begyakorolt szabadrúgás- vagy szögletvariáció",
    "szabadrúgás-/szögletvariáció",
    "álló helyzet rutin",
    "The goal came from a well-drilled set-piece routine.",
    "A gól egy jól begyakorolt szögletvariációból esett.",
  ],
  [
    "tactics",
    "tactical naivety",
    "taktikai tapasztalatlanságból, éretlenségből fakadó hiba",
    "taktikai naivitás",
    "taktikai naivitás (kontextusfüggő ragozásra figyelni)",
    "Their tactical naivety cost them the match.",
    "Taktikai naivitásuk a mérkőzésükbe került.",
  ],

  // ---------------------------------------------------------------------
  // SÉRÜLÉSEK ÉS KERETHÍREK (injury_squad)
  // ---------------------------------------------------------------------
  [
    "injury_squad",
    "hamstring injury",
    "a combhajlító izomcsoport sérülése",
    "combhajlítóizom-sérülés",
    "combhúr sérülés",
    "He suffered a hamstring injury in training.",
    "Combhajlítóizom-sérülést szenvedett az edzésen.",
  ],
  [
    "injury_squad",
    "torn ACL",
    "a keresztszalag teljes szakadása",
    "keresztszalag-szakadás",
    "elszakadt ACL",
    "Scans confirmed a torn ACL.",
    "A vizsgálatok keresztszalag-szakadást igazoltak.",
  ],
  [
    "injury_squad",
    "calf strain",
    "a vádliizom rándulása/húzódása",
    "vádliizom-húzódás",
    "borjú megerőltetés",
    "He was withdrawn with a calf strain.",
    "Vádliizom-húzódás miatt kellett lecserélni.",
  ],
  [
    "injury_squad",
    "groin injury",
    "az ágyéktáji izomzat sérülése",
    "ágyéktáji sérülés",
    "ágyék sérülés (helyes, de pontosítás jó)",
    "The defender is out with a groin injury.",
    "Ágyéktáji sérülés miatt hiányzik a védő.",
  ],
  [
    "injury_squad",
    "knock",
    "kisebb, ütődésből eredő sérülés",
    "horzsolás / kisebb ütődés",
    "kopogás (félrefordítás!)",
    "He picked up a knock in the warm-up.",
    "Kisebb ütődést szenvedett a bemelegítés során.",
  ],
  [
    "injury_squad",
    "niggle",
    "kisebb, hosszabb ideje fennálló panasz",
    "kisebb, tartós panasz",
    "csipkelődés (félrefordítás!)",
    "He has been carrying a niggle for weeks.",
    "Hetek óta egy kisebb panasszal küzd.",
  ],
  [
    "injury_squad",
    "fitness test",
    "a bevethetőséget eldöntő, edzés előtti felmérés",
    "alkalmassági teszt",
    "fitnesz teszt (elfogadható, de magyarabb forma jó)",
    "He will undergo a late fitness test.",
    "Az utolsó pillanatban esik át egy alkalmassági teszten.",
  ],
  [
    "injury_squad",
    "return to full fitness",
    "teljes fizikai felépülés egy sérülés után",
    "teljes felépülés",
    "visszatérés a teljes fitneszhez",
    "He is close to a return to full fitness.",
    "Közel áll a teljes felépüléshez.",
  ],
  [
    "injury_squad",
    "sidelined",
    "sérülés miatt nem bevethető állapot",
    "kidőlt / nem vethető be",
    "oldalra állítva",
    "He has been sidelined since March.",
    "Március óta kidőlt sérülés miatt.",
  ],
  [
    "injury_squad",
    "sidelined for weeks",
    "adott ideig tartó kihagyás sérülés miatt",
    "hetekre kidől",
    "hetekig oldalvonalon",
    "He is sidelined for six weeks.",
    "Hat hétre dől ki.",
  ],
  [
    "injury_squad",
    "long-term injury",
    "hosszú felépülési időt igénylő sérülés",
    "hosszú kihagyást jelentő sérülés",
    "hosszú távú sérülés",
    "It is a long-term injury that will require surgery.",
    "Egy hosszú kihagyást jelentő, műtétet igénylő sérülésről van szó.",
  ],
  [
    "injury_squad",
    "rule out",
    "hivatalosan kizárni valakit a szereplésből",
    "kizárja a szereplésből",
    "kizár (túl általános fordítás)",
    "The club ruled him out for the season.",
    "A klub a szezon hátralévő részére kizárta a szereplésből.",
  ],
  [
    "injury_squad",
    "doubtful",
    "kérdéses, bizonytalan a szereplése egy adott mérkőzésen",
    "kérdéses a szereplése",
    "kétséges",
    "He is doubtful for Saturday's game.",
    "Kérdéses a szombati szereplése.",
  ],
  [
    "injury_squad",
    "touch and go",
    "bizonytalan kimenetelű, szoros helyzet (felépülésre értve)",
    "bizonytalan / a végsőkig kétséges",
    "érintés és megy (félrefordítás!)",
    "It's touch and go whether he'll be fit in time.",
    "Bizonytalan, hogy időben felépül-e.",
  ],
  [
    "injury_squad",
    "scan",
    "orvosi képalkotó vizsgálat (pl. MRI)",
    "vizsgálat / felvétel",
    "szkennelés",
    "Scans revealed ligament damage.",
    "A vizsgálatok szalagsérülést mutattak ki.",
  ],
  [
    "injury_squad",
    "surgery",
    "sebészeti beavatkozás",
    "műtét",
    "sebészet",
    "He is set to undergo surgery next week.",
    "Jövő héten esik át a műtéten.",
  ],
  [
    "injury_squad",
    "rehabilitation",
    "a felépülést, edzésbe való visszatérést célzó folyamat",
    "rehabilitáció / felépülési folyamat",
    "rehab (informálisan elfogadható)",
    "He began his rehabilitation this week.",
    "Ezen a héten kezdte meg rehabilitációját.",
  ],
  [
    "injury_squad",
    "return date",
    "a visszatérés várható időpontja",
    "visszatérési időpont",
    "visszatérési dátum",
    "No return date has been set.",
    "Visszatérési időpontot még nem tűztek ki.",
  ],
  [
    "injury_squad",
    "squad rotation",
    "a kezdőcsapat tudatos, tervszerű cserélgetése",
    "keretforgatás",
    "keret rotáció",
    "The manager used squad rotation to manage fatigue.",
    "A vezetőedző keretforgatással kezelte a fáradtságot.",
  ],
  [
    "injury_squad",
    "rested",
    "pihentetve, taktikai okból kihagyva egy mérkőzésről",
    "pihentetve",
    "pihentetett (túl passzív, de elfogadható)",
    "Three regulars were rested for the cup game.",
    "Három kulcsjátékost pihentettek a kupamérkőzésre.",
  ],
  [
    "injury_squad",
    "precautionary measure",
    "elővigyázatosságból tett intézkedés",
    "elővigyázatossági intézkedés",
    "óvintézkedés (elfogadható rövidebb forma)",
    "He was withdrawn as a precautionary measure.",
    "Elővigyázatosságból cserélték le.",
  ],
  [
    "injury_squad",
    "train alone",
    "a csapattól elkülönítve, egyénileg edzeni",
    "külön edz (a kerettől elkülönítve)",
    "egyedül edz",
    "He has been training alone this week.",
    "Ezen a héten a kerettől elkülönítve edzett.",
  ],
  [
    "injury_squad",
    "full training",
    "a teljes csapattal, korlátozás nélkül végzett edzés",
    "teljes értékű csapatedzés",
    "teljes edzés",
    "He returned to full training on Monday.",
    "Hétfőn tért vissza a teljes értékű csapatedzésre.",
  ],
  [
    "injury_squad",
    "benched",
    "kispadra ültetve, a kezdőcsapatból kihagyva",
    "kispadra ültetve / kihagyva a kezdőből",
    "padra téve",
    "The captain was benched for the first time this season.",
    "A csapatkapitányt idén először ültették kispadra.",
  ],
  [
    "injury_squad",
    "dropped from the squad",
    "teljesen kihagyva a meccskeretből",
    "kihagyva a keretből",
    "leejtve a keretből",
    "He was dropped from the squad entirely.",
    "Teljesen kihagyták a meccskeretből.",
  ],
  [
    "injury_squad",
    "matchday squad",
    "az adott mérkőzésre nevezett keret",
    "meccskeret",
    "mérkőzésnapi keret",
    "He was named in the matchday squad for the first time.",
    "Először nevezték a meccskeretbe.",
  ],
  [
    "injury_squad",
    "call-up",
    "válogatottba történő meghívás",
    "válogatott behívó",
    "felhívás",
    "He received his first senior call-up.",
    "Megkapta első felnőtt válogatott behívóját.",
  ],
  [
    "injury_squad",
    "withdraw from squad",
    "sérülés/betegség miatt kilépni egy meghívott keretből",
    "visszalép a keretből",
    "kivonul a keretből",
    "He withdrew from the squad due to illness.",
    "Betegség miatt visszalépett a keretből.",
  ],
  [
    "injury_squad",
    "suspension",
    "eltiltás egy vagy több mérkőzésre",
    "eltiltás",
    "felfüggesztés",
    "He will serve a one-match suspension.",
    "Egymeccses eltiltását fogja letölteni.",
  ],
  [
    "injury_squad",
    "accumulated yellow cards",
    "több sárga lap összegyűjtése miatti eltiltás",
    "sárgalap-halmozás (miatti eltiltás)",
    "felhalmozott sárga lapok",
    "He is banned due to accumulated yellow cards.",
    "Sárgalap-halmozás miatt tiltották el.",
  ],
  [
    "injury_squad",
    "return from suspension",
    "visszatérés az eltiltás letöltése után",
    "visszatér az eltiltás után",
    "visszatérés a felfüggesztésből",
    "He returns from suspension this weekend.",
    "Ezen a hétvégén tér vissza az eltiltás után.",
  ],
  [
    "injury_squad",
    "stretchered off",
    "hordágyon, önerőből való lehagyás nélkül elhagyni a pályát",
    "hordágyon vitték le",
    "hordágyazták le (helytelen ragozás)",
    "He was stretchered off after a heavy collision.",
    "Egy komoly ütközés után hordágyon vitték le.",
  ],
  [
    "injury_squad",
    "limped off",
    "sántítva, saját lábon elhagyni a pályát sérülés miatt",
    "sántítva hagyta el a pályát",
    "biceg le",
    "He limped off in the second half.",
    "A második félidőben sántítva hagyta el a pályát.",
  ],
  [
    "injury_squad",
    "setback in recovery",
    "visszaesés a felépülési folyamat során",
    "visszaesés a felépülésben",
    "visszalépés a felépülésben",
    "He suffered a setback in his recovery.",
    "Visszaesést szenvedett a felépülésében.",
  ],
  [
    "injury_squad",
    "sidelined indefinitely",
    "meghatározatlan ideig tartó kihagyás",
    "határozatlan időre kidőlt",
    "határozatlanul oldalvonalra állítva",
    "He is sidelined indefinitely after the surgery.",
    "A műtét után határozatlan időre dőlt ki.",
  ],
  [
    "injury_squad",
    "squad depth",
    "a keret mélysége, a cserejátékosok minősége/mennyisége",
    "keretmélység",
    "keret mélység",
    "Injuries have exposed their lack of squad depth.",
    "A sérülések rávilágítottak a keretmélység hiányára.",
  ],
  [
    "injury_squad",
    "injury crisis",
    "egyszerre több kulcsjátékost érintő sérülésproblémák",
    "sérülésválság / sérülésjárvány",
    "sérülési krízis",
    "The club is dealing with an injury crisis.",
    "A klub sérülésválsággal küzd.",
  ],
  [
    "injury_squad",
    "walking wounded",
    "kisebb sérülésekkel is pályára lépő játékosok",
    "sérülten is pályára lépő játékosok",
    "sétáló sebesültek (túl szó szerinti)",
    "Several walking wounded featured in the win.",
    "Több, sérülten is pályára lépő játékos szerepelt a győzelemben.",
  ],
  [
    "injury_squad",
    "fit again",
    "ismét bevethető, sérülésmentes állapot",
    "ismét bevethető",
    "újra fitt",
    "He is fit again after a month out.",
    "Egyhavi kihagyás után ismét bevethető.",
  ],

  // ---------------------------------------------------------------------
  // EDZŐI ÉS JÁTÉKOSNYILATKOZATOK (quotes)
  // ---------------------------------------------------------------------
  [
    "quotes",
    "we take it one game at a time",
    "a csapat nem néz előre, csak a következő mérkőzésre koncentrál",
    "meccsről meccsre gondolkodunk / haladunk",
    "egy meccset veszünk egyszerre (túl szó szerinti)",
    '"We take it one game at a time," said the manager.',
    '"Meccsről meccsre haladunk" - mondta a vezetőedző.',
  ],
  [
    "quotes",
    "we need to dust ourselves off",
    "túl kell lépni egy vereségen/kudarcon",
    "fel kell állnunk / túl kell lépnünk ezen",
    "le kell porolnunk magunkat (túl szó szerinti)",
    "We need to dust ourselves off and go again.",
    "Fel kell állnunk, és folytatnunk kell.",
  ],
  [
    "quotes",
    "credit to the boys",
    "elismerés a csapatnak/játékosoknak",
    "dicséret illeti a fiúkat / a csapatot",
    "kredit a fiúknak (anglicizmus)",
    "Credit to the boys, they never gave up.",
    "Dicséret illeti a fiúkat, sosem adták fel.",
  ],
  [
    "quotes",
    "it is what it is",
    "el kell fogadni a helyzetet, ahogy van",
    "ez van / el kell fogadnunk",
    "az az, ami (túl szó szerinti)",
    "It is what it is, we move on.",
    "Ez van, továbblépünk.",
  ],
  [
    "quotes",
    "we go again",
    "folytatjuk, nem adjuk fel a következő kihívás előtt",
    "megyünk tovább / folytatjuk",
    "megyünk megint",
    "Disappointing result, but we go again on Saturday.",
    "Csalódást keltő eredmény, de szombaton megyünk tovább.",
  ],
  [
    "quotes",
    "we're disappointed with the result",
    "elégedetlenség kifejezése az eredménnyel kapcsolatban",
    "csalódottak vagyunk az eredmény miatt",
    "csalódottak vagyunk az eredménnyel (rossz vonzat)",
    "We're disappointed with the result, but not the performance.",
    "Csalódottak vagyunk az eredmény miatt, de nem a teljesítmény miatt.",
  ],
  [
    "quotes",
    "we controlled the game",
    "a csapat uralta, kézben tartotta a mérkőzést",
    "kézben tartottuk a mérkőzést",
    "kontrolláltuk a játékot (anglicizmus)",
    "We controlled the game from start to finish.",
    "Elejétől a végéig kézben tartottuk a mérkőzést.",
  ],
  [
    "quotes",
    "we need to be more clinical",
    "hatékonyabban kell kihasználni a helyzeteket",
    "hatékonyabbnak kell lennünk a befejezésnél",
    "klinikaibbnak kell lennünk (félrefordítás!)",
    "We need to be more clinical in front of goal.",
    "Hatékonyabbnak kell lennünk a kapu előtt.",
  ],
  [
    "quotes",
    "the lads gave everything",
    "a játékosok mindent megtettek, maximális erőfeszítést tettek",
    "a fiúk mindent beleadtak",
    'a fiúk mindent adtak (helyes is, de "beleadtak" természetesebb)',
    "The lads gave everything out there today.",
    "A fiúk ma mindent beleadtak a pályán.",
  ],
  [
    "quotes",
    "we can take a lot of positives",
    "sok jó dolgot lehet levonni a teljesítményből vereség ellenére is",
    "sok pozitívumot vihetünk magunkkal",
    "sok pozitívot vehetünk (rossz szórend/ragozás)",
    "We can take a lot of positives from this performance.",
    "Sok pozitívumot vihetünk magunkkal ebből a teljesítményből.",
  ],
  [
    "quotes",
    "at the end of the day",
    "végső soron, amikor minden számít",
    "végső soron / amikor minden lezajlik",
    "a nap végén (túl szó szerinti)",
    "At the end of the day, we need the points.",
    "Végső soron a pontokra van szükségünk.",
  ],
  [
    "quotes",
    "we're taking it step by step",
    "fokozatosan, egyik lépésről a másikra haladva",
    "lépésről lépésre haladunk",
    "lépésenként vesszük (rossz vonzat)",
    "We're taking it step by step this season.",
    "Ebben a szezonban lépésről lépésre haladunk.",
  ],
  [
    "quotes",
    "the boys showed great character",
    "a csapat nagy jellembeli erőt, kiállást mutatott",
    "a srácok nagy jellemről tettek tanúbizonyságot",
    "a fiúk nagy karaktert mutattak (anglicizmus)",
    "The boys showed great character to come back.",
    "A srácok nagy jellemről tettek tanúbizonyságot a fordítással.",
  ],
  [
    "quotes",
    "we're not getting carried away",
    "nem esnek túlzásba, nem lesznek elbizakodottak egy jó eredmény után",
    "nem esünk túlzásba / nem kapjuk fel a fejünket",
    "nem visszük el magunkat (félrefordítás!)",
    "We're not getting carried away after one win.",
    "Egy győzelem után nem kapjuk fel a fejünket.",
  ],
  [
    "quotes",
    "it's a squad game",
    "a siker nem egy-két emberen, hanem az egész kereten múlik",
    "keretmunka ez / az egész kereten múlik",
    "ez egy keretjáték (túl szó szerinti)",
    "Football is a squad game these days.",
    "A mai futball keretmunka.",
  ],
  [
    "quotes",
    "he's a warrior",
    "harcos szellemű, önfeláldozó játékos",
    "harcos alkat / igazi harcos",
    "harcos (önmagában, kontextus nélkül furcsa)",
    "He's a warrior, he never hides.",
    "Igazi harcos, sosem bújik el a felelősség elől.",
  ],
  [
    "quotes",
    "he leaves everything out there",
    "teljes erőbedobással, kímélet nélkül játszik",
    "mindent kitesz a pályára",
    "mindent otthagy ott kint (túl szó szerinti)",
    "He leaves everything out there every single week.",
    "Minden egyes héten mindent kitesz a pályára.",
  ],
  [
    "quotes",
    "we're building something special",
    "hosszú távon értékes, kiemelkedő projektet építenek",
    "valami különlegeset építünk",
    "valami speciálisat építünk (anglicizmus)",
    "We believe we're building something special here.",
    "Hiszünk benne, hogy valami különlegeset építünk itt.",
  ],
  [
    "quotes",
    "we have to dig deep",
    "rendkívüli erőfeszítést, kitartást kell mutatni",
    "a végsőkig kell küzdenünk",
    "mélyre kell ásnunk (túl szó szerinti)",
    "We had to dig deep in the second half.",
    "A második félidőben a végsőkig kellett küzdenünk.",
  ],
  [
    "quotes",
    "we're in a good place",
    "a csapat jó formában, jó hangulatban van",
    "jó helyzetben / jó formában vagyunk",
    "jó helyen vagyunk (kétértelmű, félrevezető)",
    "Mentally, we're in a good place right now.",
    "Mentálisan jó formában vagyunk most.",
  ],
  [
    "quotes",
    "we need to learn from this",
    "a kudarcból tanulságot kell levonni",
    "tanulnunk kell ebből",
    'tanulnunk kell ebből (helyes, de gyakran hozzáteszik: "és fejlődnünk")',
    "We need to learn from this and improve.",
    "Tanulnunk kell ebből, és fejlődnünk kell.",
  ],
  [
    "quotes",
    "we're gutted",
    "mélységesen csalódottak, lesújtottak",
    "nagyon rosszul érintett minket / mélységesen csalódottak vagyunk",
    "ki vagyunk béleletlenítve (félrefordítás!)",
    "We're gutted to lose in the last minute.",
    "Mélységesen csalódottak vagyunk az utolsó perces vereség miatt.",
  ],
  [
    "quotes",
    "we can't afford to switch off",
    "nem szabad megengedni a koncentráció lankadását",
    "nem engedhetjük meg magunknak, hogy kikapcsoljunk",
    "nem engedhetjük meg a kikapcsolást (rossz vonzat)",
    "We can't afford to switch off for even a minute.",
    "Egy percre sem engedhetjük meg magunknak, hogy lankadjon a figyelmünk.",
  ],
  [
    "quotes",
    "we stuck to the game plan",
    "következetesen tartották magukat az előre megbeszélt taktikához",
    "tartottuk magunkat a mérkőzéstervhez",
    "ragaszkodtunk a játéktervhez (elfogadható, de kevésbé természetes)",
    "We stuck to the game plan and it paid off.",
    "Tartottuk magunkat a mérkőzéstervhez, és ez kifizetődött.",
  ],
  [
    "quotes",
    "we need a reaction",
    "a csapatnak megfelelő választ, javulást kell mutatnia egy kudarc után",
    "reakcióra van szükség a csapattól",
    "reakciót igényelünk (rossz vonzat)",
    "We need a reaction from everyone on Saturday.",
    "Szombaton mindenkitől reakcióra van szükség.",
  ],
  [
    "quotes",
    "he's a class act",
    "kiemelkedő minőségű, klasszis játékos",
    "klasszis",
    "ő egy osztály cselekvés (félrefordítás!)",
    "He's a class act both on and off the pitch.",
    "A pályán és azon kívül is klasszis.",
  ],
  [
    "quotes",
    "he's been immense",
    "kiemelkedően nagy teljesítményt nyújtott",
    "óriási teljesítményt nyújtott",
    "hatalmas volt (elfogadható, de kevésbé szakszerű)",
    "He's been immense for us all season.",
    "Egész szezonban óriási teljesítményt nyújtott nekünk.",
  ],
  [
    "quotes",
    "we're proud of the boys",
    "büszkeség kifejezése a csapat iránt",
    "büszkék vagyunk a fiúkra",
    "büszkék vagyunk a fiúkról (rossz vonzat)",
    "We're proud of the boys for their effort.",
    "Büszkék vagyunk a fiúkra az erőfeszítésükért.",
  ],
  [
    "quotes",
    "we have to move on quickly",
    "gyorsan túl kell lépni egy eseményen (győzelmen vagy vereségen)",
    "gyorsan túl kell lépnünk ezen",
    "gyorsan tovább kell mozdulnunk (túl szó szerinti)",
    "We have to move on quickly to the next game.",
    "Gyorsan túl kell lépnünk ezen a következő meccs miatt.",
  ],
  [
    "quotes",
    "he's a leader in the dressing room",
    "informális, közösségformáló vezető szerepet tölt be a csapaton belül",
    "vezéregyéniség az öltözőben",
    "vezető az öltözőszobában (túl szó szerinti)",
    "He's a natural leader in the dressing room.",
    "Természetes vezéregyéniség az öltözőben.",
  ],
  [
    "quotes",
    "we take confidence from that",
    "önbizalmat merítenek egy pozitív eseményből",
    "önbizalmat merítünk ebből",
    "bizalmat veszünk abból (rossz vonzat)",
    "We take a lot of confidence from that win.",
    "Sok önbizalmat merítünk ebből a győzelemből.",
  ],
  [
    "quotes",
    "we're building momentum",
    "egyre jobb formába lendülnek, lendületet gyűjtenek",
    "lendületet gyűjtünk",
    'lendületet építünk (elfogadható, de "gyűjtünk" természetesebb)',
    "We're building momentum at just the right time.",
    "Éppen a megfelelő időben gyűjtünk lendületet.",
  ],
  [
    "quotes",
    "we need to be ruthless",
    "kíméletlenül, a lehetőségeket maximálisan kihasználva kell játszani",
    "könyörtelennek kell lennünk",
    "kegyetlennek kell lennünk (túl szó szerinti, negatív felhang)",
    "We need to be ruthless in front of goal.",
    "Könyörtelennek kell lennünk a kapu előtt.",
  ],
  [
    "quotes",
    "he's a fantastic professional",
    "példamutató, szakmailag igényes hozzáállású játékos",
    "kiváló profi",
    "fantasztikus professzionális (túl szó szerinti)",
    "He's a fantastic professional both on and off the pitch.",
    "A pályán és azon kívül is kiváló profi.",
  ],
  [
    "quotes",
    "we let ourselves down",
    "önmagukhoz képest alulteljesítettek, csalódást okoztak maguknak",
    "cserben hagytuk magunkat",
    "leengedtük magunkat (félrefordítás!)",
    "We let ourselves down with our defending today.",
    "A védekezésünkkel ma cserben hagytuk magunkat.",
  ],
  [
    "quotes",
    "it wasn't our day",
    "a csapatnak egyszerűen nem jött össze semmi az adott napon",
    "nem ez volt a mi napunk",
    "ez nem volt a mi napunk (elfogadható is)",
    "It just wasn't our day today.",
    "Ma egyszerűen nem ez volt a mi napunk.",
  ],
  [
    "quotes",
    "we're hurting",
    "mélyen érinti, fájdalmat okoz egy vereség/kudarc",
    "fáj ez nekünk",
    "sérülünk (félrefordítás! testi sérülésre utalna)",
    "We're hurting after that defeat.",
    "Nagyon fáj nekünk ez a vereség.",
  ],

  // ---------------------------------------------------------------------
  // BRIT FUTBALLSZLENG ÉS IDIOMATIKUS FORDULATOK (slang_idiom)
  // ---------------------------------------------------------------------
  [
    "slang_idiom",
    "over the moon",
    "rendkívül boldog, örömteli állapot",
    "földöntúli boldogság / a fellegekben jár",
    "a hold felett vagyunk (túl szó szerinti)",
    "The manager was over the moon with the win.",
    "A vezetőedző a fellegekben járt a győzelem után.",
  ],
  [
    "slang_idiom",
    "sick as a parrot",
    "mélységesen csalódott, lehangolt állapot (brit szleng)",
    "mélységesen csalódott",
    "beteg, mint egy papagáj (szó szerint értelmetlen)",
    "He was sick as a parrot after missing the penalty.",
    "Mélységesen csalódott volt a kihagyott tizenegyes után.",
  ],
  [
    "slang_idiom",
    "park the bus",
    "extrém, kizárólag védekezésre épülő taktika",
    "beparkolja a buszt / falig védekezik",
    "leparkolja a buszt (elfogadható is, elterjedt magyarul)",
    "The visitors parked the bus for the entire match.",
    "A vendégek az egész mérkőzésen beparkolták a buszt.",
  ],
  [
    "slang_idiom",
    "hit the woodwork",
    "kapufát/keresztlécet találni el",
    "kapufát lő",
    "eltalálja a fás munkát (félrefordítás!)",
    "He hit the woodwork twice in the first half.",
    "Az első félidőben kétszer is kapufát lőtt.",
  ],
  [
    "slang_idiom",
    "game of two halves",
    "fordulatos mérkőzésre utaló brit szólás",
    "fordulatos meccs volt",
    "két félidő játéka (túl szó szerinti)",
    "It was a game of two halves out there.",
    "Igazán fordulatos meccs volt ez a mai.",
  ],
  [
    "slang_idiom",
    "sitter",
    "könnyű, kihagyhatatlannak tűnő helyzet, amit mégis kihagynak",
    "ziccer / helyzet, amit nem lehetne kihagyni",
    "ülő alkalom (félrefordítás!)",
    "He missed an absolute sitter in the second half.",
    "A második félidőben egy hatalmas ziccert hagyott ki.",
  ],
  [
    "slang_idiom",
    "worldie",
    "kiemelkedően szép, világklasszis gól vagy megoldás",
    "világklasszis gól / bombagól",
    '"világi" gól (félrefordítás!)',
    "That was an absolute worldie from outside the box.",
    "Ez egy tökéletes bombagól volt a tizenhatoson kívülről.",
  ],
  [
    "slang_idiom",
    "screamer",
    "erőteljes, látványos, gyakran nagy távolságból eltalált gól",
    "bombagól",
    "sikoltó (félrefordítás!)",
    "He scored an absolute screamer from 25 yards.",
    "Egy 25 méterről eltalált bombagólt szerzett.",
  ],
  [
    "slang_idiom",
    "banter",
    "baráti, jó szándékú ugratás, froclizás",
    "ugratás / froclizás",
    "banter (angolosan, kerülendő)",
    "There's a lot of friendly banter between the two squads.",
    "Sok baráti froclizás zajlik a két keret között.",
  ],
  [
    "slang_idiom",
    "gaffer",
    "az edző becéző, informális megnevezése",
    "mester / edző (beceneve)",
    "gaffer (angolosan, kerülendő)",
    "The gaffer praised the team's effort.",
    "A mester dicsérte a csapat erőfeszítését.",
  ],
  [
    "slang_idiom",
    "squeaky bum time",
    "a szezon idegtépő, feszült záró szakasza",
    "idegtépő hajrá (a szezon vége felé)",
    "nyikorgó fenék idő (szó szerint értelmetlen)",
    "It's squeaky bum time in the title race.",
    "Idegtépő hajrájához érkezett a bajnoki cím körüli harc.",
  ],
  [
    "slang_idiom",
    "smash and grab",
    "gyenge teljesítmény mellett, szerencsével elért győzelem",
    "szerencsés győzelem (gyenge játék ellenére)",
    "üss és ragadd meg (szó szerint értelmetlen)",
    "It was a smash and grab win on the road.",
    "Szerencsés idegenbeli győzelmet arattak.",
  ],
  [
    "slang_idiom",
    "backs to the wall",
    "teljes védekezésre kényszerülő, szorult helyzet",
    "falhoz szorítva / a végsőkig védekezve",
    "hátak a falnak (túl szó szerinti)",
    "They had their backs to the wall for the final ten minutes.",
    "Az utolsó tíz percben a falhoz szorítva védekeztek.",
  ],
  [
    "slang_idiom",
    "cup fever",
    "a kupasorozat iránti fokozott, közösségi izgalom",
    "kupaláz",
    "kupa láz (két szóban, kerülendő)",
    "Cup fever has gripped the small town.",
    "Kupaláz szállta meg a kisvárost.",
  ],
  [
    "slang_idiom",
    "giant-killers",
    "nagy esélytelenből győztes, jóval erősebb ellenfelet legyőző csapat",
    "óriásölő csapat / esélytelenből győztes",
    "óriás gyilkosok (túl erős, félrevezető)",
    "The giant-killers advance to the next round.",
    "Az óriásölő csapat továbbjutott a következő fordulóba.",
  ],
  [
    "slang_idiom",
    "minnows",
    "a mezőny esélytelen, kisebb csapata",
    "esélytelen/kisebb csapat",
    "pikóhalak (szó szerint helytelen kontextusban)",
    "The minnows shocked the favourites.",
    "Az esélytelen kisebb csapat megleckéztette a favoritokat.",
  ],
  [
    "slang_idiom",
    "journeyman",
    "sok különböző klubnál megforduló, vándorló pályafutású játékos",
    "vándorló pályafutású játékos",
    "utazó ember (szó szerint helytelen)",
    "He's been a journeyman throughout his career.",
    "Pályafutása során mindvégig vándorló játékos volt.",
  ],
  [
    "slang_idiom",
    "cult hero",
    "a szurkolók által különösen kedvelt, kultstátuszú játékos",
    "kultstátuszú kedvenc",
    'kultusz hős (elfogadható, de "kultstátuszú" természetesebb)',
    "He became a cult hero at the club.",
    "Kultstátuszú kedvenccé vált a klubnál.",
  ],
  [
    "slang_idiom",
    "the beautiful game",
    "a futball költői, gyakran használt beceneve",
    '"a szép játék"',
    "a szép játék (helyes, idézőjelben ajánlott)",
    "That's why they call it the beautiful game.",
    'Ezért hívják "a szép játéknak".',
  ],
  [
    "slang_idiom",
    "bragging rights",
    "a helyi rangadó győztesét megillető, jelképes dicsekvési jog",
    "dicsekvési jog (a rangadó győztesének)",
    "kérkedési jogok (elfogadható, kevésbé elterjedt)",
    "The win secured local bragging rights.",
    "A győzelem biztosította a helyi dicsekvési jogot.",
  ],
  [
    "slang_idiom",
    "hammering",
    "kiütéses, egyértelmű vereség",
    "kiütéses vereség",
    "kalapálás (szó szerint értelmetlen)",
    "It was a 5-0 hammering at home.",
    "5-0-s kiütéses vereséget szenvedtek otthon.",
  ],
  [
    "slang_idiom",
    "mauling",
    "komoly, megalázó mértékű vereség",
    "komoly, megalázó vereség",
    "megtépázás (szó szerint furcsa)",
    "The champions suffered a mauling in the semi-final.",
    "A bajnokcsapat megalázó vereséget szenvedett az elődöntőben.",
  ],
  [
    "slang_idiom",
    "dressing room bust-up",
    "az öltözőben zajló, nyilvánosságra kerülő konfliktus",
    "öltözői összezördülés",
    "öltöző kirobbanás (túl szó szerinti)",
    "Reports emerged of a dressing room bust-up.",
    "Hírek jelentek meg egy öltözői összezördülésről.",
  ],
  [
    "slang_idiom",
    "super-sub",
    "csereként rendszeresen mérkőzést eldöntő játékos",
    "szuperbeálló",
    "szuper csere (elfogadható is)",
    "He has built a reputation as a super-sub.",
    "Szuperbeállóként szerzett hírnevet magának.",
  ],
  [
    "slang_idiom",
    "wonderkid",
    "kiemelkedő tehetségű, fiatal, ígéretes játékos",
    "csodagyerek",
    "csoda gyerek (két szóban, kerülendő)",
    "The wonderkid made his debut aged just 16.",
    "A csodagyerek mindössze 16 évesen mutatkozott be.",
  ],
  [
    "slang_idiom",
    "down to the bare bones",
    "sérülésekkel súlyosan megtizedelt, minimális létszámú keret",
    "minimálisra tizedelt keret",
    "csontokig lecsupaszítva (túl szó szerinti)",
    "Injuries have left the squad down to the bare bones.",
    "A sérülések minimálisra tizedelték a keretet.",
  ],
  [
    "slang_idiom",
    "keep the faith",
    "kitartani a bizalom, a hit mellett nehéz időszakban is",
    "kitart a bizalom mellett",
    "tartsa meg a hitet (túl szó szerinti)",
    "The fans continue to keep the faith.",
    "A szurkolók továbbra is kitartanak a bizalom mellett.",
  ],
  [
    "slang_idiom",
    "dark horse",
    "meglepetésre esélyes, alábecsült versenyző/csapat",
    "meglepetésre esélyes csapat",
    "sötét ló (szó szerint értelmetlen)",
    "They could be the dark horse of the competition.",
    "Ők lehetnek a sorozat meglepetésre esélyes csapata.",
  ],
  [
    "slang_idiom",
    "blow the game wide open",
    "teljesen kiegyenlítetlenné, eldöntetlenné tenni a mérkőzés kimenetelét",
    "teljesen kinyitja a meccset",
    "szélesre fújja a játékot (szó szerint értelmetlen)",
    "The red card blew the game wide open.",
    "A kiállítás teljesen kinyitotta a mérkőzést.",
  ],
  [
    "slang_idiom",
    "a game of chess",
    "taktikus, kiszámított, lassú tempójú mérkőzés",
    "sakkjátszmához hasonló mérkőzés",
    "egy sakkjáték (szó szerinti, de elfogadható)",
    "It was a tactical game of chess between the two managers.",
    "A két vezetőedző között taktikus sakkjátszma zajlott.",
  ],
  [
    "slang_idiom",
    "relegation dogfight",
    "a kiesés elleni, több csapatot érintő szoros küzdelem",
    "kieső helyekért folyó harc",
    "kiesési kutyaharc (szó szerint furcsa)",
    "They are caught up in a relegation dogfight.",
    "Benne ragadtak a kieső helyekért folyó harcban.",
  ],
  [
    "slang_idiom",
    "top-four scrap",
    "a Bajnokok Ligája-indulást érő helyekért folyó küzdelem",
    "Bajnokok Ligája-helyekért folyó harc",
    "top-négy csetepaté (túl szó szerinti)",
    "It's a genuine top-four scrap this season.",
    "Igazi harc folyik idén a Bajnokok Ligája-helyekért.",
  ],
  [
    "slang_idiom",
    "handbags",
    "komolytalan, inkább szóváltásból álló összezördülés a pályán",
    "szócsata / komolytalan dulakodás",
    "kézitáskák (szó szerint értelmetlen)",
    "It was just handbags between the two players.",
    "Csak egy komolytalan szócsata volt a két játékos között.",
  ],
  [
    "slang_idiom",
    "a bit of previous",
    "két fél között fennálló régi konfliktus, előzmény",
    "régi konfliktus / előzmény",
    "egy kis korábbi (túl szó szerinti)",
    "There's a bit of previous between these two clubs.",
    "Régi konfliktus húzódik e két klub között.",
  ],
  [
    "slang_idiom",
    "talking a good game",
    "csak szavakban, tettek nélkül ígérgető hozzáállás",
    "csak beszél, tettek nélkül",
    "jó játékot beszél (túl szó szerinti)",
    "They're talking a good game, but need to prove it on the pitch.",
    "Csak beszélnek, de a pályán kell bizonyítaniuk.",
  ],
  [
    "slang_idiom",
    "put in a shift",
    "keményen, fáradhatatlanul dolgozni a pályán",
    "keményen dolgozik / robotol a pályán",
    "berak egy műszakot (túl szó szerinti)",
    "He put in a real shift in midfield.",
    "Igazán keményen robotolt a középpályán.",
  ],
  [
    "slang_idiom",
    "go route one",
    "közvetlen, hosszú labdákra épülő, egyszerű játékstílus",
    "hosszúlabdás, direkt játékot alkalmaz",
    "megy az egyes útvonalon (szó szerint értelmetlen)",
    "They went route one in the closing stages.",
    "A záró szakaszban hosszúlabdás, direkt játékra váltottak.",
  ],
  [
    "slang_idiom",
    "get stuck in",
    "harciasan, kemény testi kontaktussal játszani",
    "keményen / harciasan játszik",
    "beleragad (félrefordítás!)",
    "The midfielder got stuck in from the first minute.",
    "A középpályás az első perctől kezdve harciasan játszott.",
  ],
  [
    "slang_idiom",
    "lose the dressing room",
    "elveszíteni a játékosok bizalmát, tekintélyét vezetőként",
    "elveszti az öltöző bizalmát",
    "elveszíti az öltözőt (rövidítve is elfogadható)",
    "There are signs the manager has lost the dressing room.",
    "Jelek mutatnak arra, hogy a vezetőedző elvesztette az öltöző bizalmát.",
  ],
  [
    "slang_idiom",
    "a game too far",
    "a fáradtság miatt már túl soknak bizonyuló, plusz mérkőzés",
    "egy meccssel több (a fáradtságra utalva)",
    "egy játék túl messzire (túl szó szerinti)",
    "This proved to be a game too far for the tired squad.",
    "Ez egy meccssel többnek bizonyult a fáradt keret számára.",
  ],
  [
    "slang_idiom",
    "daylight robbery",
    "kirívóan igazságtalan, a csapatot hátrányosan érintő bírói döntés",
    '"rablás" (igazságtalan bírói döntésre)',
    "nappali rablás (szó szerint furcsa)",
    "That penalty decision was daylight robbery.",
    "Az a tizenegyes-döntés kész rablás volt.",
  ],

  // ---------------------------------------------------------------------
  // KIEGÉSZÍTŐ TÉTELEK (a 300-as minimum eléréséhez, kategóriánként)
  // ---------------------------------------------------------------------
  [
    "injury_squad",
    "on the treatment table",
    "kezelés alatt áll sérülés miatt",
    "kezelőasztalon van",
    "a kezelőasztalon (szó szerint, de furcsa önmagában)",
    "He has spent most of the season on the treatment table.",
    "A szezon nagy részét kezelőasztalon töltötte.",
  ],
  [
    "injury_squad",
    "precautionary scan",
    "elővigyázatosságból, súlyosabb gyanú nélkül végzett vizsgálat",
    "elővigyázatosságból végzett vizsgálat",
    "óvatossági szkennelés",
    "He underwent a precautionary scan after the game.",
    "A mérkőzés után elővigyázatosságból vizsgálatot végeztek rajta.",
  ],
  [
    "injury_squad",
    "return to training",
    "visszatérés a csapatedzésekre felépülés után",
    "visszatérés az edzésekre",
    "edzésre való visszatérés (elfogadható is)",
    "His return to training is a boost for the squad.",
    "Az edzésekre való visszatérése erőt ad a keretnek.",
  ],
  [
    "injury_squad",
    "medical staff",
    "a klub orvosi/fizioterápiás szakembergárdája",
    "orvosi stáb",
    "orvosi személyzet (elfogadható is)",
    "The medical staff confirmed the extent of the injury.",
    "Az orvosi stáb megerősítette a sérülés súlyosságát.",
  ],
  [
    "injury_squad",
    "long-term absentee",
    "hosszabb ideje, tartósan hiányzó játékos",
    "hosszú távon hiányzó játékos",
    "hosszú távú távollévő",
    "He has been a long-term absentee since the autumn.",
    "Ősz óta hosszú távon hiányzó játékosnak számít.",
  ],
  [
    "injury_squad",
    "muscle fatigue",
    "az izomzat túlterhelésből eredő elfáradása",
    "izomfáradtság",
    "izom fáradtság (két szóban, kerülendő)",
    "He was withdrawn due to muscle fatigue.",
    "Izomfáradtság miatt kellett lecserélni.",
  ],
  [
    "injury_squad",
    "assess him overnight",
    "egy éjszakán át megfigyelés alatt tartani az állapotát",
    "egy éjszakán át megfigyelik az állapotát",
    "felmérik éjszakán át (elfogadható, kevésbé természetes)",
    "The club will assess him overnight.",
    "A klub egy éjszakán át megfigyeli majd az állapotát.",
  ],
  [
    "injury_squad",
    "expected to be out for months",
    "hosszú, több hónapos kihagyás várható",
    "várhatóan hónapokig hiányzik",
    "várhatóan kint lesz hónapokig (túl szó szerinti)",
    "He is expected to be out for at least three months.",
    "Várhatóan legalább három hónapig hiányzik.",
  ],

  [
    "quotes",
    "we take each game as it comes",
    "nem néznek előre, mérkőzésenként koncentrálnak",
    "úgy vesszük a mérkőzéseket, ahogy jönnek",
    "minden meccset úgy veszünk, ahogy jön (rossz szórend)",
    "We take each game as it comes at this stage.",
    "Ebben a szakaszban úgy vesszük a mérkőzéseket, ahogy jönnek.",
  ],
  [
    "quotes",
    "the lads deserve credit",
    "a csapat elismerést érdemel a teljesítményéért",
    "a fiúk elismerést érdemelnek",
    "a fiúk kreditet érdemelnek (anglicizmus)",
    "The lads deserve credit for that response.",
    "A fiúk elismerést érdemelnek ezért a reakcióért.",
  ],
  [
    "quotes",
    "we're heading in the right direction",
    "a csapat fejlődése, formája kedvező irányba tart",
    "jó irányba haladunk",
    "jó irányba fejünk (félrefordítás!)",
    "I believe we're heading in the right direction.",
    "Hiszem, hogy jó irányba haladunk.",
  ],
  [
    "quotes",
    "we need to dig ourselves out of this",
    "nehéz, kedvezőtlen helyzetből kell kilábalni",
    "ki kell ásnunk magunkat ebből a helyzetből",
    "ki kell ásnunk magunkat ebből (elfogadható is)",
    "We need to dig ourselves out of this hole.",
    "Ki kell ásnunk magunkat ebből a gödörből.",
  ],
  [
    "quotes",
    "he's a model professional",
    "példamutató, mintaszerű hozzáállású játékos",
    "példamutató profi",
    "modell profi (félrefordítás!)",
    "He's a model professional around the training ground.",
    "Az edzőközpontban is példamutató profi.",
  ],
  [
    "quotes",
    "we're taking each day as it comes",
    "napról napra, előretervezés nélkül haladnak",
    "napról napra haladunk",
    "minden napot úgy veszünk, ahogy jön (rossz szórend)",
    "In recovery, we're taking each day as it comes.",
    "A felépülésben napról napra haladunk.",
  ],
  [
    "quotes",
    "we know we can do better",
    "a csapat tudatában van, hogy jobb teljesítményre képes",
    "tudjuk, hogy tudunk jobbat nyújtani",
    "tudjuk, hogy jobbat tehetünk (elfogadható, kevésbé szakszerű)",
    "We know we can do better than that.",
    "Tudjuk, hogy ennél jobbat is tudunk nyújtani.",
  ],
  [
    "quotes",
    "we're fighting for our lives",
    "a kiesés elleni, létfontosságú küzdelemre utaló fordulat",
    "az életünkért harcolunk (a kiesés ellen)",
    "harcolunk az életeinkért (túl szó szerinti)",
    "We're fighting for our lives at the bottom of the table.",
    "A tabella alján az életünkért harcolunk.",
  ],

  [
    "slang_idiom",
    "form book",
    "a csapatok/játékosok korábbi eredményeit összegző, esélyeket jelző referencia",
    "forma-könyv / papírforma",
    "forma könyv (két szóban, kerülendő)",
    "Throw the form book out the window for a derby.",
    "Egy rangadón a papírforma nem sokat számít.",
  ],
  [
    "slang_idiom",
    "the form book counts for nothing",
    "a korábbi eredmények, esélyek nem garantálnak semmit egy adott mérkőzésen",
    "a papírforma semmit sem ér",
    "a forma könyv semmit sem számít (túl szó szerinti)",
    "In a cup tie, the form book counts for nothing.",
    "Egy kupamérkőzésen a papírforma semmit sem ér.",
  ],
  [
    "slang_idiom",
    "the table doesn't lie",
    "a bajnoki tabella állása objektíven tükrözi a teljesítményt",
    "a tabella nem hazudik",
    "az asztal nem hazudik (félrefordítás!)",
    "After 20 games, the table doesn't lie.",
    "20 forduló után a tabella nem hazudik.",
  ],
  [
    "slang_idiom",
    "no love lost",
    "nyílt ellenszenv, rivalizálás két fél között",
    "nincs szimpátia (a felek között)",
    "nincs elveszett szerelem (szó szerint értelmetlen)",
    "There's no love lost between these two clubs.",
    "Nincs szimpátia e két klub között.",
  ],
  [
    "slang_idiom",
    "cup final atmosphere",
    "a döntőkre jellemző, rendkívül feszült, ünnepi hangulat",
    "kupadöntő-hangulat",
    "kupa döntő atmoszféra (elfogadható, kevésbé tömör)",
    "The stadium had a genuine cup final atmosphere.",
    "A stadionban valódi kupadöntő-hangulat uralkodott.",
  ],
  [
    "slang_idiom",
    "roar of the crowd",
    "a szurkolók hangos, egyöntetű ováció-szerű megnyilvánulása",
    "a közönség ordítása / hangzavara",
    "a tömeg üvöltése (elfogadható is)",
    "The roar of the crowd lifted the home side.",
    "A közönség ordítása szárnyakat adott a hazaiaknak.",
  ],
  [
    "slang_idiom",
    "backed into a corner",
    "kilátástalan, szorult helyzetbe kényszerítve",
    "sarokba szorítva",
    "hátrahúzva egy sarokba (túl szó szerinti)",
    "The manager felt backed into a corner over team selection.",
    "A vezetőedző sarokba szorítva érezte magát a csapatösszeállítás miatt.",
  ],

  [
    "tactics",
    "high line",
    "magasan tartott, kockázatosabb védelmi vonal",
    "magas védelmi vonal",
    "magas sor (túl szó szerinti)",
    "Their high line was repeatedly exposed on the counter.",
    "Magas védelmi vonaluk többször is sebezhetőnek bizonyult kontránál.",
  ],
  [
    "tactics",
    "low press",
    "az ellenfél térfelén nem, csak mélyebben kezdeményezett letámadás",
    "alacsony/mély letámadás",
    "alacsony nyomás (túl szó szerinti)",
    "They opted for a low press to conserve energy.",
    "Az energia megőrzése érdekében mélyebb letámadás mellett döntöttek.",
  ],
  [
    "tactics",
    "defensive shape",
    "a csapat védekezésben felvett, összehangolt alakzata",
    "védekező alakzat",
    "defenzív forma",
    "They lost their defensive shape after the substitution.",
    "A csere után elvesztették védekező alakzatukat.",
  ],
  [
    "tactics",
    "space in behind",
    "a védősor mögötti, kihasználható üres terület",
    "tér a védelem mögött",
    "hely mögötte (túl szó szerinti)",
    "The striker exploited the space in behind all game.",
    "A csatár egész meccsen kihasználta a védelem mögötti teret.",
  ],

  [
    "match_report",
    "added-time winner",
    "a hosszabbításban szerzett győztes gól",
    "hosszabbításban szerzett győztes gól",
    "hozzáadott idős győztes (túl szó szerinti)",
    "An added-time winner sparked wild celebrations.",
    "A hosszabbításban szerzett győztes gól vad ünneplést váltott ki.",
  ],
  [
    "match_report",
    "goal drought",
    "hosszabb ideje tartó, gólok nélküli időszak",
    "gólcsőd / gólínség",
    "gólaszály (elfogadható is, elterjedt)",
    "He ended a five-match goal drought.",
    "Öt meccses gólcsődjét törte meg.",
  ],
  [
    "match_report",
    "unbeaten run",
    "vereség nélküli mérkőzések sorozata",
    "veretlenségi sorozat",
    "verhetetlen sorozat (elfogadható, kevésbé elterjedt)",
    "Their unbeaten run reached ten games.",
    "Veretlenségi sorozatuk tíz mérkőzésig tartott.",
  ],
  [
    "match_report",
    "winning streak",
    "egymást követő győzelmek sorozata",
    "győzelmi sorozat",
    "nyerő sorozat (elfogadható, kevésbé szakszerű)",
    "The win extended their winning streak to six.",
    "A győzelemmel hat meccsesre nyújtották győzelmi sorozatukat.",
  ],

  [
    "transfer",
    "loan spell",
    "a kölcsönben töltött időszak egésze",
    "kölcsönjáték időszaka",
    "kölcsön varázslat (félrefordítás!)",
    "His loan spell at the club was a huge success.",
    "Kölcsönjátéka a klubnál óriási siker volt.",
  ],
  [
    "transfer",
    "transfer saga",
    "hosszan elhúzódó, sok fordulatot hozó átigazolási történet",
    "elhúzódó átigazolási dráma",
    "átigazolási saga (angolos, kerülendő)",
    "The transfer saga finally came to an end.",
    "Az elhúzódó átigazolási dráma végre lezárult.",
  ],
  [
    "transfer",
    "medical scheduled",
    "az orvosi vizsgálat időpontjának kitűzése",
    "orvosi vizsgálat kitűzve",
    "orvosi ütemezve (túl szó szerinti)",
    "His medical is scheduled for Wednesday.",
    "Orvosi vizsgálatát szerdára tűzték ki.",
  ],
  [
    "transfer",
    "contract talks",
    "a szerződéses feltételekről folyó tárgyalások",
    "szerződéses tárgyalások",
    "szerződés beszélgetések (túl szó szerinti)",
    "Contract talks are progressing well.",
    "A szerződéses tárgyalások jól haladnak.",
  ],
];

export const FOOTBALL_LEXICON: LexiconEntry[] = RAW.map(
  ([category, en, meaningHu, naturalHu, avoidLiteralHu, exampleEn, exampleHu]) => ({
    category,
    en,
    meaningHu,
    naturalHu,
    avoidLiteralHu,
    exampleEn,
    exampleHu,
  }),
);

/**
 * Case-insensitive, szóhatáros keresés: visszaadja a lexikon azon tételeit,
 * amelyek angol kifejezése (`en`) ténylegesen előfordul a megadott szövegben.
 * Csak a releváns tételeket adja vissza — a teljes 300+ elemes lexikon
 * minden hívásba való begépeselése kezelhetetlenül megnövelné a prompt
 * méretét/költségét, miközben a legtöbb tétel az adott cikkhez nem
 * kapcsolódna.
 */
export function findRelevantLexiconEntries(text: string, limit = 20): LexiconEntry[] {
  const haystack = text.toLowerCase();
  const matches = FOOTBALL_LEXICON.filter((entry) => {
    const needle = entry.en.toLowerCase();
    const escaped = needle.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return new RegExp(`\\b${escaped}\\b`, "i").test(haystack) || haystack.includes(needle);
  });
  return matches.slice(0, limit);
}

/** Kompakt, LLM-prompt-ba illeszthető blokk a talált tételekből. */
export function formatLexiconBlock(entries: LexiconEntry[]): string {
  if (entries.length === 0) {
    return "";
  }
  const lines = entries.map(
    (e) => `- "${e.en}" → ${e.naturalHu} (NE: "${e.avoidLiteralHu}"; jelentés: ${e.meaningHu})`,
  );
  return `FUTBALLNYELVI SZÓTÁR — a szövegben felismerhető angol futballkifejezések magyar megfelelői (ezt használd, ne tükörfordítást):\n${lines.join("\n")}`;
}
